
bike:
      database:
            url: jdbc:postgresql://localhost:5432/bikedb
            username: postgres
            password: 1234

television:
      database:
            url: jdbc:postgresql://localhost:5432/televisiondb
            username: postgres
            password: 1234

earphone:
      database:
            url: jdbc:postgresql://localhost:5432/earphonedb
            username: postgres
            password: 1234

pendrive:
      database:
            url: jdbc:postgresql://localhost:5432/pendrivedb
            username: postgres
            password: 1234



