bike:
      database:
            url: jdbc:postgresql://localhost:5432/bikedb
            username: postgres
            password: 1234


television:
      database:
            url: jdbc:postgresql://localhost:5432/televisiondb
            username: postgres
            password: 1234




